import * as esbuild from "esbuild";

await esbuild.build({
  entryPoints: [
    "src/index.ts",
    "src/animations/index.ts",
    "src/core/index.ts",
    "src/common/index.ts",
    "src/core/platform/index.ts",
    "src/cdk/a11y/index.ts",
    "src/cdk/layout/index.ts",
    "src/i18n/index.ts",
    "src/i18n/locales/en.ts",
    "src/i18n/locales/es-MX.ts",
    "src/rxjs-interop/index.ts",
    "src/platform-browser/index.ts",
    "src/runtime/common/index.ts",
    "src/runtime/animations/index.ts",
    "src/runtime/i18n/index.ts",
    "src/runtime/cdk/a11y/index.ts",
    "src/runtime/cdk/layout/index.ts",
    "src/runtime/platform-browser/index.ts",
    "src/runtime/testing/index.ts",
    "src/compat/index.ts",
    "src/router/index.ts",
  ],
  bundle: true,
  format: "esm",
  splitting: true,
  outdir: "dist",
  outbase: "src",
  platform: "browser",
  external: [
    "angular",
    "angular-animate",
    "angular-translate",
    "angular-aria",
    "rxjs",
    "rxjs/*",
    "zone.js",
    "zone.js/*",
    "@uirouter/angularjs",
  ],
  sourcemap: true,
  target: ["es2022"],
});
